import { ProfileState } from 'src/types';

export const USERS: ProfileState[] = [
  {
    id: 'user1',
    login: 'admin',
    password: 'admin',
    accessLevel: 777,
    firstName: 'Андрей',
    middleName: 'Дмитриевич',
    lastName: 'Поляков',
    birthday: '1994-02-25',
    mail: 'admin@admin.ru',
  },
  {
    id: 'user2',
    login: 'user2',
    password: 'user2',
    accessLevel: 5,
    firstName: '',
    middleName: '',
    lastName: '',
    birthday: '1994-02-25',
    mail: 'user2@hobbium.ru',
  },
  {
    id: 'user3',
    login: 'user3',
    password: 'user3',
    accessLevel: 5,
    firstName: '',
    middleName: '',
    lastName: '',
    birthday: '1994-02-25',
    mail: 'user3@hobbium.ru',
  },
  {
    id: 'user4',
    login: 'user4',
    password: 'user4',
    accessLevel: 5,
    firstName: '',
    middleName: '',
    lastName: '',
    birthday: '1994-02-25',
    mail: 'user4@hobbium.ru',
  },
  {
    id: 'user5',
    login: 'user5',
    password: 'user5',
    accessLevel: 5,
    firstName: '',
    middleName: '',
    lastName: '',
    birthday: '1994-02-25',
    mail: 'user5@hobbium.ru',
  },
  {
    id: 'user6',
    login: 'user6',
    password: 'user6',
    accessLevel: 5,
    firstName: '',
    middleName: '',
    lastName: '',
    birthday: '1994-02-25',
    mail: 'user6@hobbium.ru',
  },
];
