export { AuthPage } from './AuthPage/AuthPage'
export { HomePage } from './HomePage/HomePage'
export { ProfilePage} from './ProfilePage/ProfilePage'
export { DashboardPage } from './DashboardPage/DashboardPage'
export { CartPage } from './CartPage/CartPage'